---
abstract: 'Library for resolving shared library dependencies for dpkg-based systems'
author:
  - huakim
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DPKG-ShlibDeps-Resolve
requires:
  Algorithm::Loops: '0'
  DPKG::Parse::Info: '0'
  Dpkg::Shlibs: '0'
  Dpkg::Shlibs::Objdump: '0'
  Exporter: '0'
  File::Find: '0'
  File::Spec: '0'
  List::Util: '0'
  warnings: '0'
resources:
  homepage: https://github.com/huakim-tyk/DPKG-ShlibDeps-Resolve
version: 0.0.4
x_generated_by_perl: v5.36.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
